var GZEoVQk=0;var PDgDmFxgcJl=false;var KsSCSLHJvRNcQ=0;var VVsDFOusRlKi=jQuery ('<div>', {attr: {'style': 'position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: 99998; user-select: none;background: #000; opacity: 0.85;'}});var TJjRNBtezrCyal=jQuery ('<div>', {attr: {'style': 'position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 99999; background: #000; color: #fff; user-select: none;width: 300px; padding: 10px; border: 5px solid #f00; border-radius: 5px;'}, html: '<p><strong>Blocked because of Ad Blocker</strong></p><p>It seems that you are using some ad blocking software which is preventing the page from fully loading. Please whitelist this website or disable ad blocking software.</p>'});;var unUpinTNb=0;var gSyRawKJF="aiADB";var DnXMAQzCdGuC="aiADB_PV";var DZvnbKz="aiADB_PR";var xhUCGmefnps=0;var vYheDJCLDe=0;
var QjwdyPLcd=0;var aHiDsMIKCR="";var biBYAUYA="";
function rGrwOiKA(){(function($){$(".trqxhshusdxii").each(function(){var KUmmfnvHl=$(this).parent();var xVhivzSpLfvYAc=$(this).data("css");if(typeof xVhivzSpLfvYAc=="undefined")xVhivzSpLfvYAc="display: none !important;";var aHiDsMIKCR=$(this).data("selectors");if(typeof aHiDsMIKCR=="undefined"||aHiDsMIKCR=="")aHiDsMIKCR="p";var vYheDJCLDe=false;$(KUmmfnvHl).find(".trqxhshusdxii, "+aHiDsMIKCR).each(function(){if($(this).hasClass("trqxhshusdxii")){$(this).remove();
vYheDJCLDe=true}else if($(this).hasClass("imlakysztpbh")){$(this).remove();vYheDJCLDe=false}else if(vYheDJCLDe){var wEtThhqf=$(this).attr("style");if(typeof wEtThhqf=="undefined")wEtThhqf="";$(this).attr("style",wEtThhqf+";"+xVhivzSpLfvYAc)}})});$(".xoumildfsvmn").each(function(){var KUmmfnvHl=$(this).parent();var aHiDsMIKCR=$(this).data("selectors");if(typeof aHiDsMIKCR=="undefined"||aHiDsMIKCR=="")aHiDsMIKCR="p";
var vYheDJCLDe=false;$(KUmmfnvHl).find(".xoumildfsvmn, "+aHiDsMIKCR).each(function(){if($(this).hasClass("xoumildfsvmn")){$(this).remove();vYheDJCLDe=true}else if($(this).hasClass("pkwyjfkufvt")){$(this).remove();vYheDJCLDe=false}else if(vYheDJCLDe)$(this).remove()})});$(".vnowuluifgrrjw").each(function(){var KUmmfnvHl=$(this).parent();var AwhZpwLuSKVU=$(this).data("text");if(typeof AwhZpwLuSKVU==
"undefined")AwhZpwLuSKVU="";var xVhivzSpLfvYAc=$(this).data("css");if(typeof xVhivzSpLfvYAc=="undefined")xVhivzSpLfvYAc="";var aHiDsMIKCR=$(this).data("selectors");if(typeof aHiDsMIKCR=="undefined"||aHiDsMIKCR=="")aHiDsMIKCR="p";var vYheDJCLDe=false;$(KUmmfnvHl).find(".vnowuluifgrrjw, "+aHiDsMIKCR).each(function(){if($(this).hasClass("vnowuluifgrrjw")){$(this).remove();vYheDJCLDe=true}else if($(this).hasClass("ejxszhpyqu")){$(this).remove();
vYheDJCLDe=false}else if(vYheDJCLDe){if(AwhZpwLuSKVU.length!=0){var n=Math.round($(this).text().length/(AwhZpwLuSKVU.length+1));$(this).text(Array(n+1).join(AwhZpwLuSKVU+" "))}else $(this).text("");var wEtThhqf=$(this).attr("style");if(typeof wEtThhqf=="undefined")wEtThhqf="";$(this).attr("style",wEtThhqf+";"+xVhivzSpLfvYAc)}})})})(jQuery)}
var qMiBmYesB=function(n){if(!PDgDmFxgcJl){PDgDmFxgcJl=true;(function($){$(window).ready(function(){$(".ai-adb-show").each(function(){$(this).css({"display":"block","visibility":"visible"});if(GZEoVQk)var debug_info=$(this).attr("data")});$(".ai-adb-hide").each(function(){$(this).css({"display":"none","visibility":"hidden"});if(GZEoVQk)var debug_info=$(this).attr("data")});setTimeout(rGrwOiKA,10)});if(QjwdyPLcd!=0){var OEyogCUAerVd=1;var cookie=$.cookie(DnXMAQzCdGuC);if(typeof cookie!="undefined")OEyogCUAerVd=parseInt(cookie)+1;if(OEyogCUAerVd<QjwdyPLcd){var d1=OEyogCUAerVd;;$.cookie(DnXMAQzCdGuC,OEyogCUAerVd,{expires:365,path:"/"});return}}if(xhUCGmefnps!=0&&(vYheDJCLDe!=1||!unUpinTNb)){var cookie=$.cookie(gSyRawKJF);if(typeof cookie!="undefined"&&cookie=="cefadeea"){var AI_ADB_STATUS_MESSAGE=
2;return}$.cookie(gSyRawKJF,"cefadeea",{expires:xhUCGmefnps,path:"/"})}else $.removeCookie(gSyRawKJF,{path:"/"});;switch(vYheDJCLDe){case 1:if(!unUpinTNb){VVsDFOusRlKi.click(function(){$(this).remove();TJjRNBtezrCyal.remove()}).css("cursor","pointer");TJjRNBtezrCyal.click(function(){$(this).remove();VVsDFOusRlKi.remove()}).css("cursor","pointer");window.onkeydown=function(event){if(event.keyCode===
27){VVsDFOusRlKi.click();TJjRNBtezrCyal.click()}}}else;$("body").prepend(VVsDFOusRlKi).prepend(TJjRNBtezrCyal);break;case 2:if(biBYAUYA!=""){var redirect=true;if(biBYAUYA.toLowerCase().substring(0,4)=="http"){if(window.location.href==biBYAUYA)var redirect=false}else if(window.location.pathname==biBYAUYA)var redirect=false;if(redirect){var cookie=$.cookie(DZvnbKz);if(typeof cookie=="undefined"){var date=
new Date;date.setTime(date.getTime()+10*1E3);$.cookie(DZvnbKz,window.location.href,{expires:date,path:"/"});window.location.replace(biBYAUYA)}else;}else jQuery.removeCookie(DZvnbKz,{path:"/"})}break}})(jQuery)}};var XYxZIJOtc=function(n){KsSCSLHJvRNcQ++;if(!PDgDmFxgcJl&&KsSCSLHJvRNcQ==3){}};if(0)jQuery(document).ready(function(){qMiBmYesB(0)});
if(!document.getElementById("dpAvZbS"))jQuery(document).ready(function(){if(!PDgDmFxgcJl||GZEoVQk)qMiBmYesB(1)});else jQuery(document).ready(function(){XYxZIJOtc(1)});if(typeof window.eKoKgKoJNxbNpS=="undefined")jQuery(document).ready(function(){if(!PDgDmFxgcJl||GZEoVQk)qMiBmYesB(2)});else jQuery(document).ready(function(){XYxZIJOtc(2)});
jQuery(document).ready(function($){$(window).ready(function(){$("#ai-adb-bar").click(function(){$.removeCookie(gSyRawKJF,{path:"/"});$.removeCookie(DnXMAQzCdGuC,{path:"/"});});if($("#banner-advert-container img").length>0){if($("#banner-advert-container img").outerHeight()===0)$(document).ready(function(){if(!PDgDmFxgcJl||GZEoVQk)qMiBmYesB(3)});else $(document).ready(function(){XYxZIJOtc(3)});$("#banner-advert-container img").remove()}if((!PDgDmFxgcJl||
GZEoVQk)&&aHiDsMIKCR!=""){var zuKbolgGhjf=0;var QnLjZtTC=0;var GqXrsaag=aHiDsMIKCR.split(",");$.each(GqXrsaag,function(i){if($(GqXrsaag[i]).length!=0)$(GqXrsaag[i]).each(function(n){zuKbolgGhjf++;if($(this).outerHeight()===0){$(document).ready(function(){if(!PDgDmFxgcJl||GZEoVQk)qMiBmYesB(4)});QnLjZtTC++;if(!GZEoVQk)return false}})});if(zuKbolgGhjf!=0&&QnLjZtTC==0)$(document).ready(function(){XYxZIJOtc(4)})}})});
(function(factory){if(typeof define==="function"&&define.amd)define(["jquery"],factory);else if(typeof exports==="object")factory(require("jquery"));else factory(jQuery)})(function($){var pluses=/\+/g;function encode(s){return config.raw?s:encodeURIComponent(s)}function decode(s){return config.raw?s:decodeURIComponent(s)}function stringifyCookieValue(value){return encode(config.json?JSON.stringify(value):String(value))}function parseCookieValue(s){if(s.indexOf('"')===0)s=s.slice(1,-1).replace(/\\"/g,
'"').replace(/\\\\/g,"\\");try{s=decodeURIComponent(s.replace(pluses," "));return config.json?JSON.parse(s):s}catch(e){}}function read(s,converter){var value=config.raw?s:parseCookieValue(s);return $.isFunction(converter)?converter(value):value}var config=$.cookie=function(key,value,options){if(value!==undefined&&!$.isFunction(value)){options=$.extend({},config.defaults,options);if(typeof options.expires==="number"){var days=options.expires,t=options.expires=new Date;t.setTime(+t+days*864E5)}return document.cookie=
[encode(key),"=",stringifyCookieValue(value),options.expires?"; expires="+options.expires.toUTCString():"",options.path?"; path="+options.path:"",options.domain?"; domain="+options.domain:"",options.secure?"; secure":""].join("")}var result=key?undefined:{};var cookies=document.cookie?document.cookie.split("; "):[];for(var i=0,l=cookies.length;i<l;i++){var parts=cookies[i].split("=");var name=decode(parts.shift());var cookie=parts.join("=");if(key&&key===name){result=read(cookie,value);break}if(!key&&
(cookie=read(cookie))!==undefined)result[name]=cookie}return result};config.defaults={};$.removeCookie=function(key,options){if($.cookie(key)===undefined)return false;$.cookie(key,"",$.extend({},options,{expires:-1}));return!$.cookie(key)}});
if(typeof sQmrRfmWPAHVl==="undefined")jQuery(document).ready(function(){if(!PDgDmFxgcJl||GZEoVQk)qMiBmYesB(5)});else{sQmrRfmWPAHVl.onDetected(function(){if(!PDgDmFxgcJl||GZEoVQk)qMiBmYesB(5)});sQmrRfmWPAHVl.onNotDetected(function(){XYxZIJOtc(5)})}
if(typeof cRzTeRKk==="undefined")jQuery(document).ready(function(){if(!PDgDmFxgcJl||GZEoVQk)qMiBmYesB(6)});else cRzTeRKk.on(true,function(){if(!PDgDmFxgcJl||GZEoVQk)qMiBmYesB(6)}).on(false,function(){XYxZIJOtc(6)});cRzTeRKk=undefined;EZtGNIyTUxmeMa=undefined;